accent = "#50a3b5"
cursor = "#fba02f"
foreground = "#deb88d"
background = "#08131a"
selection_foreground = "#deb88d"
selection_background = "#1e4862"

color0 = "#0f2838"
color1 = "#d05023"
color2 = "#027b9b"
color3 = "#fba02f"
color4 = "#2d6870"
color5 = "#68d3f0"
color6 = "#50a3b5"
color7 = "#deb88d"
color8 = "#424b52"
color9 = "#d38677"
color10 = "#618c98"
color11 = "#fdd29e"
color12 = "#1abcdd"
color13 = "#bbe3ee"
color14 = "#86abb3"
color15 = "#fee3cd"
