[colors]
[colors.primary]
background = '#e0d6c8'
foreground = '#0f2838'

# Normal colors
[colors.normal]
black = '#f5efe7'
red = '#d05023'
green = '#027b9b'
yellow = '#d88821'
blue = '#2d6870'
magenta = '#68d3f0'
cyan = '#50a3b5'
white = '#0f2838'

# Bright colors
[colors.bright]
black = '#7d8891'
red = '#d38677'
green = '#618c98'
yellow = '#fba02f'
blue = '#1abcdd'
magenta = '#4a9fb5'
cyan = '#86abb3'
white = '#08131a'

[colors.selection]
background = '#c8dde8'
