accent = "#50a3b5"
cursor = "#d05023"
foreground = "#0f2838"
background = "#e0d6c8"
selection_foreground = "#0f2838"
selection_background = "#c8dde8"

color0 = "#b8a796"
color1 = "#d05023"
color2 = "#027b9b"
color3 = "#d88821"
color4 = "#2d6870"
color5 = "#0f7b8a"
color6 = "#50a3b5"
color7 = "#0f2838"
color8 = "#4a5a65"
color9 = "#d38677"
color10 = "#618c98"
color11 = "#c57a1a"
color12 = "#0e8fb5"
color13 = "#2d6870"
color14 = "#3a6a75"
color15 = "#08131a"
